# Generated by Django 4.2 on 2024-07-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_client_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('change_newsletter_status', 'Может менять статус рассылок'), ('view_newsletter_details', 'Может просматривать детали рассылок'), ('can_users_out', 'Может отключать пользователей'), ('view_newsletter_users', 'Может просматривать пользователей')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
